### ISSUE TITLE
Use a proper SONAME for libshaderc.so

### ISSUE THREAD

**Issue by haasn** [google/shaderc#381]
Instead of arbitrarily calling it `libshaderc_shared.so` it should be called `libshaderc.so.VER` where VER encodes the ABI version. This would also allow users to compile with `-lshaderc` universally instead of needing to change it to `-lshaderc_shared` to build a dynamically linked executable.

For more information see https://en.wikipedia.org/wiki/Soname

**Comment by dneto0** [comment]
Fixed by #493

**Comment by haasn** [comment]
There's just one thing I'd still like to nitpick about. You still appear to call it `libshaderc_shared.so.1` rather than the more conventional/canonical `libshaderc.so.1`. Any reason for why this should be the case?

**Comment by dneto0** [comment]
I paged that out of my brain.  I think @AWoloszyn might remember.

**Comment by AWoloszyn** [comment]
I think @antiagainst was the one who added shaderc_shared.

If I remember correctly, it was because for some reason we couldn't or didn't want to use the  cmake BUILD_SHARED_LIBS flag to get a shared library out.

We end up building both libshaderc.a and libshaderc_shared.so, and they are named as such because CMake does not allow two targets to have the same name. We can probably fix this with a simple 

```
set_target_properties(shaderc_shared OUTPUT_NAME shaderc)
```

Although looking at the documentation I am not sure if we would also have to specify the extension/prefix, in which case that would get a bit more complicated.

**Comment by antiagainst** [comment]
@Kangz added shared library via https://github.com/google/shaderc/pull/366.

I'm not sure we can give the same name to both the static and shared library on Windows:

https://stackoverflow.com/questions/2152077/is-it-possible-to-get-cmake-to-build-both-a-static-and-shared-version-of-the-sam

But I don't have a strong preference.

**Comment by AWoloszyn** [comment]
I think we would be better off with the BUILD_SHARED_LIBS approach. We should be able to detect, and then build one or the other, and then the user gets to choose.

**Comment by haasn** [comment]
I think the usual approach is to let the user choose the build type (shared vs static). For most users, I don't see much of a point in building both at the same time.

**Comment by antiagainst** [comment]
I've uploaded #498 for this.
